services:
  app:
    build:
      context: .
    command: gunicorn --access-logfile - -b "0.0.0.0:8000" "app.main:create_app()"
    # command: flask run -h 0.0.0.0 -p 8000 --debug
    environment:
      FLASK_APP: app.main
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./app:/app
